### ISSUE TITLE
loadPlaylist from url, that servers a json

### ISSUE THREAD

**Issue by u8887** [internet4000/radio4000-player#115] opened 2018-07-23 08:21 UTC
It would be interesting to see what we can do with loading the player directly from a json representation similar to what is passed to `loadPlaylist`

**Comment by oskarrough** [comment] 2019-08-18 12:57
duplicate of https://github.com/internet4000/radio4000-player/issues/104?

**Closed by oskarrough** 2019-08-18 12:57 UTC
